require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'

local suburbsDistribution = {
    all = {
        inventoryfemale = {
            items = {
                "iMeds.BismuthSubsalicylatePack", 0.001,
                "iMeds.AlkaginPack", 0.001,
                "iMeds.UmifenovirPack", 0.001,
                "iMeds.UnknownPack", 0.001,
                "iMeds.ButamiratePack", 0.001,
                "iMeds.HemoStopPack", 0.001,
                "iMeds.SyringePack", 0.001,
                "iMeds.NeedlePack", 0.001,
                "iMeds.BloodTestingKit", 0.001,
            }
        },
        inventorymale = {
            items = {
                "Pills", 0,
                "PillsAntiDep", 0.1,
                "PillsBeta", 0.1,
                "PillsVitamins", 0,
                "iMeds.HemoStopPack", 0.001,
                "iMeds.BismuthSubsalicylatePack", 0.001,
                "iMeds.AlkaginPack", 0.001,
                "iMeds.UmifenovirPack", 0.001,
                "iMeds.UnknownPack", 0.001,
                "iMeds.ButamiratePack", 0.001,
                "iMeds.HemoStopPack", 0.001,
                "iMeds.SyringePack", 0.001,
                "iMeds.NeedlePack", 0.001,
                "iMeds.BloodTestingKit", 0.001,
            }
        },
        medicine = {
            items = {
                "iMeds.BismuthSubsalicylatePack", 0.03,
                "iMeds.AlkaginPack", 0.05,
                "iMeds.UmifenovirPack", 0.03,
                "iMeds.MorphinePack", 0.03,
                "iMeds.UnknownPack", 2,
                "iMeds.ButamiratePack", 0.05,
                "iMeds.BismuthSubsalicylatePack", 0.05,
                "iMeds.HemoStopPack", 0.03,
                "iMeds.PeripheralVenousCatheter", 1,
                "iMeds.EmptyBloodBag", 1,
                "iMeds.BloodTestingKit", 4,
            },
        },
    },

    Bag_BigHikingBag = {
        items = {
            "iMeds.BismuthSubsalicylatePack", 0.03,
            "iMeds.AlkaginPack", 0.05,
            "iMeds.UmifenovirPack", 0.03,
            "iMeds.UnknownPack", 0.03,
            "iMeds.ButamiratePack", 0.05,
            "iMeds.BismuthSubsalicylatePack", 0.05,
            "iMeds.HemoStopPack", 0.03,
            "iMeds.SyringePack", 0.03,
            "iMeds.NeedlePack", 0.03,
        },
        fillRand = 1,
    },

    Bag_NormalHikingBag = {
        items = {
            "iMeds.BismuthSubsalicylatePack", 0.03,
            "iMeds.AlkaginPack", 0.05,
            "iMeds.UmifenovirPack", 0.03,
            "iMeds.UnknownPack", 0.03,
            "iMeds.ButamiratePack", 0.05,
            "iMeds.BismuthSubsalicylatePack", 0.05,
            "iMeds.HemoStopPack", 0.03,
            "iMeds.SyringePack", 0.03,
            "iMeds.NeedlePack", 0.03,
        },
        fillRand = 1,
    },

    Bag_SurvivorBag = {
        items = {
            "iMeds.BismuthSubsalicylatePack", 0.03,
            "iMeds.AlkaginPack", 0.05,
            "iMeds.UmifenovirPack", 0.03,
            "iMeds.UnknownPack", 0.03,
            "iMeds.ButamiratePack", 0.05,
            "iMeds.BismuthSubsalicylatePack", 0.05,
            "iMeds.HemoStopPack", 0.03,
            "iMeds.PeripheralVenousCatheter", 0.03,
            "iMeds.EmptyBloodBag", 0.03,
            "iMeds.BloodTestingKit", 0.03,
            "iMeds.SyringePack", 0.03,
            "iMeds.NeedlePack", 0.03,
        },
        -- only two map allowed
        maxMap = 2,
        -- this mean 90% chance on normal sandbox settings to have an annoted map
        stashChance = 10,
        fillRand = 0,
    },

    FirstAidKit = {
        rolls = 1,
        items = {
            "iMeds.UnknownPack", 0.03,
            "iMeds.UnknownPack", 0.03,
            "iMeds.UnknownPack", 0.03,
            "iMeds.ButamiratePack", 0.05,
            "iMeds.BismuthSubsalicylatePack", 0.05,
            "iMeds.HemoStopPack", 0.03,
            "iMeds.PeripheralVenousCatheter", 0.03,
            "iMeds.PeripheralVenousCatheter", 0.03,
            "iMeds.PeripheralVenousCatheter", 0.03,
            "iMeds.PeripheralVenousCatheter", 0.03,
            "iMeds.AlkaginPack", 0.05,
            "iMeds.AlkaginPack", 0.05,
            "iMeds.UmifenovirPack", 0.03,
            "iMeds.BloodTestingKit", 0.03,
            "iMeds.BloodTestingKit", 0.03,
            "iMeds.BloodTestingKit", 0.03,
            "iMeds.BloodTestingKit", 0.03,
            "iMeds.SyringePack", 0.5,
            "iMeds.SyringePack", 0.5,
            "iMeds.NeedlePack", 0.5,
            "iMeds.NeedlePack", 0.5,
        },
        fillRand = 0,
    },
}

local proceduralDistributions = {
    list = {
        ArmyStorageMedical = {
            items = {
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.MorphinePack", 2,
                "iMeds.UnknownPack", 4,
                "iMeds.UnknownPack", 4,
                "iMeds.UnknownPack", 4,
                "iMeds.UnknownPack", 4,
                "iMeds.ButamiratePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.HemoStopPack", 4,
                "iMeds.HemoStopPack", 4,
                "iMeds.PeripheralVenousCatheter", 5,
                "iMeds.PeripheralVenousCatheter", 5,
                "iMeds.PeripheralVenousCatheter", 5,
                "iMeds.PeripheralVenousCatheter", 5,
                "iMeds.EmptyBloodBag", 5,
                "iMeds.EmptyBloodBag", 5,
                "iMeds.EmptyBloodBag", 5,
                "iMeds.EmptyBloodBag", 5,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.SyringePack", 10,
                "iMeds.SyringePack", 10,
                "iMeds.NeedlePack", 10,
                "iMeds.NeedlePack", 10,
            },
        },

        BathroomCounterNoMeds = {
            items = {
                "iMeds.UnknownPack", 0.03,
                "iMeds.UnknownPack", 0.03,
                "iMeds.SyringePack", 0.5,
                "iMeds.NeedlePack", 0.5,
            },
        },

        MedicalClinicDrugs = {
            items = {
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.MorphinePack", 5,
                "iMeds.MorphinePack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.ButamiratePack", 10,
                "iMeds.ButamiratePack", 10,
                "iMeds.ButamiratePack", 10,
                "iMeds.ButamiratePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.HemoStopPack", 5,
                "iMeds.HemoStopPack", 5,
                "iMeds.HemoStopPack", 5,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
            },
        },

        MedicalClinicOutfit = {
            items = {
                "iMeds.UnknownPack", 5,
                "iMeds.EmptyBloodBag", 1,
                "iMeds.EmptyBloodBag", 1,
                "iMeds.BloodTestingKit", 4,
                "iMeds.BloodTestingKit", 4,
                "iMeds.SyringePack", 5,
                "iMeds.NeedlePack", 5,
            },
        },

        MedicalClinicTools = {
            items = {
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
            },
        },

        MedicalStorageDrugs = {
            items = {
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.MorphinePack", 5,
                "iMeds.MorphinePack", 5,
                "iMeds.MorphinePack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.ButamiratePack", 10,
                "iMeds.ButamiratePack", 10,
                "iMeds.ButamiratePack", 10,
                "iMeds.ButamiratePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.HemoStopPack", 5,
                "iMeds.HemoStopPack", 5,
            },
        },

        MedicalStorageTools = {
            items = {
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.PeripheralVenousCatheter", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.EmptyBloodBag", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.BloodTestingKit", 10,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.SyringePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
                "iMeds.NeedlePack", 20,
            },
        },

        StoreShelfMedical = {
            items = {
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.AlkaginPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UmifenovirPack", 10,
                "iMeds.UnknownPack", 5,
                "iMeds.UnknownPack", 5,
                "iMeds.ButamiratePack", 10,
                "iMeds.ButamiratePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.BismuthSubsalicylatePack", 10,
                "iMeds.HemoStopPack", 5,
                "iMeds.HemoStopPack", 5,
                "iMeds.SyringePack", 10,
                "iMeds.SyringePack", 10,
                "iMeds.NeedlePack", 10,
                "iMeds.NeedlePack", 10,
            },
        },
    }
}

for location, data in pairs(suburbsDistribution.all) do
    for _, value in ipairs(data.items) do
        table.insert(SuburbsDistributions['all'][location].items, value);
    end
end

for location, data in pairs(proceduralDistributions.list) do
    for _, value in ipairs(data.items) do
        table.insert(ProceduralDistributions['list'][location].items, value);
    end
end
